spring:
  datasource:
    url: jdbc:h2:mem:sygotchi;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: admin
    password:
  h2:
    console:
      path: /db
      enabled: true
      settings:
        web-allow-others: true
server:
  ssl:
    key-store-password: CodingCamp123
    key-store: ssl/localhost-ssl.p12
    key-store-type: PKCS12
    enabled: true

